kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands: 
      - dotnet sonarscanner begin /k:"easv-devops_Calculator_AY2OZEsIEVvRW2O60D6o" /d:sonar.host.url="http://sonar.setgo.dk:9000"  /d:sonar.token="sqp_ab1ab28f6ee0ff1e685b29a701e8985041a55991"
      - dotnet build 
      - dotnet sonarscanner end /d:sonar.token="sqp_ab1ab28f6ee0ff1e685b29a701e8985041a55991"
